/**
 * PDF Parser - Extract text and convert PDF to image for OCR
 * Uses pdf.js for PDF processing
 */

import * as pdfjsLib from "pdfjs-dist";

// Configure pdf.js worker
pdfjsLib.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjsLib.version}/pdf.worker.min.js`;

export interface PdfTextResult {
  text: string;
  hasText: boolean;
  pageCount: number;
}

/**
 * Extract native text from a PDF file
 * Works best for PDFs generated by software (invoices, etc.)
 * @param file PDF file to extract text from
 * @returns Extracted text and metadata
 */
export async function extractTextFromPdf(file: File): Promise<PdfTextResult> {
  try {
    const arrayBuffer = await file.arrayBuffer();
    const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;

    let fullText = "";
    const pageCount = pdf.numPages;

    // Extract text from first 3 pages (enough for most invoices)
    const pagesToProcess = Math.min(pageCount, 3);

    for (let i = 1; i <= pagesToProcess; i++) {
      const page = await pdf.getPage(i);
      const textContent = await page.getTextContent();

      const pageText = textContent.items.map((item: any) => item.str).join(" ");

      fullText += pageText + "\n";
    }

    // Clean up the text
    fullText = fullText.replace(/\s+/g, " ").trim();

    return {
      text: fullText,
      hasText: fullText.length > 50, // Consider "has text" if more than 50 chars
      pageCount,
    };
  } catch (error) {
    console.error("Error extracting text from PDF:", error);
    return {
      text: "",
      hasText: false,
      pageCount: 0,
    };
  }
}

/**
 * Convert the first page of a PDF to an image (for OCR fallback)
 * @param file PDF file to convert
 * @param scale Scale factor for rendering (2 = 2x resolution for better OCR)
 * @returns Blob containing the rendered image
 */
export async function convertPdfToImage(
  file: File,
  scale: number = 2
): Promise<Blob> {
  const arrayBuffer = await file.arrayBuffer();
  const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;

  // Get the first page
  const page = await pdf.getPage(1);
  const viewport = page.getViewport({ scale });

  // Create canvas
  const canvas = document.createElement("canvas");
  const context = canvas.getContext("2d");

  if (!context) {
    throw new Error("Could not get canvas context");
  }

  canvas.width = viewport.width;
  canvas.height = viewport.height;

  // Render PDF page to canvas
  await page.render({
    canvasContext: context,
    viewport: viewport,
  }).promise;

  // Convert canvas to blob
  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => {
        if (blob) {
          resolve(blob);
        } else {
          reject(new Error("Failed to convert canvas to blob"));
        }
      },
      "image/png",
      1.0
    );
  });
}

/**
 * Check if a file is a PDF
 */
export function isPdfFile(file: File): boolean {
  return (
    file.type === "application/pdf" || file.name.toLowerCase().endsWith(".pdf")
  );
}
