// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-contacts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_contacts_default = defineTool({
  name: "list_contacts",
  title: "List clients / contacts",
  description: "List the clients (contacts) belonging to the signed-in user's organization. Optionally filter by a search term matching name or email.",
  inputSchema: {
    search: z.string().trim().optional().describe("Optional substring to search in name or email."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("contacts").select("id, name, email, phone, city, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (search && search.length > 0) {
      q = q.or(`name.ilike.%${search}%,email.ilike.%${search}%`);
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { contacts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-invoices.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_invoices_default = defineTool2({
  name: "list_invoices",
  title: "List invoices",
  description: "List invoices for the signed-in user's organization, most recent first. Optionally filter by status.",
  inputSchema: {
    status: z2.enum(["draft", "sent", "paid", "partial", "overdue", "cancelled"]).optional().describe("Filter by invoice status."),
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("invoices").select("id, number, date, due_date, status, subtotal, tax_amount, total, amount_paid, contact_id").order("date", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { invoices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-quotes.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_quotes_default = defineTool3({
  name: "list_quotes",
  title: "List quotes (devis)",
  description: "List quotes for the signed-in user's organization, most recent first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const { data, error } = await sb.from("quotes").select("id, number, date, status, total, contact_id, subject").order("date", { ascending: false }).limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { quotes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-prospects.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.90.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_prospects_default = defineTool4({
  name: "list_prospects",
  title: "List prospects (CRM)",
  description: "List CRM prospects for the signed-in user's organization. Optionally filter by search term (name or company).",
  inputSchema: {
    search: z4.string().trim().optional(),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    let q = sb.from("prospects").select("id, name, company_name, email, phone, city, status_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (search && search.length > 0) {
      q = q.or(`name.ilike.%${search}%,company_name.ilike.%${search}%`);
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { prospects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
var whoami_default = defineTool5({
  name: "whoami",
  title: "Who am I",
  description: "Return the identity of the currently authenticated My Business Suite user (id and email).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dazdotcdpudxpycodbbe";
var mcp_default = defineMcp({
  name: "my-business-suite-mcp",
  title: "My Business Suite",
  version: "0.1.0",
  instructions: "Tools for My Business Suite (Factura). Each tool acts as the signed-in user: list their clients (contacts), invoices, quotes (devis), and CRM prospects. Use `whoami` to verify the connected identity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_contacts_default,
    list_invoices_default,
    list_quotes_default,
    list_prospects_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
